version: "3.8"
services:
  db:
    image: postgres:16
    container_name: onedc-postgres
    environment:
      POSTGRES_USER: ts_user
      POSTGRES_PASSWORD: ts_pass
      POSTGRES_DB: ondcdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ts_user -d ondcdb"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
